### ISSUE TITLE
Design Database

### ISSUE THREAD

**Issue by giahuyngh16** [truc-nguyen-vn/CNPMNC-WEB#10]

**Comment by truc-nguyen-vn** [comment]
- [ ] Project Analysis, Requirement Analysis
- [ ] Design Model, ERD

**Comment by giahuyngh16** [comment]
**NhanVien(_IDNV_, IDType, Email ,Pass TenNV, DienThoai, DiaChi, Cmnd, Avatar)**
- [ ]  Quản lý tạo tài khoản và thông tin cho nhân viên
- [ ] Mỗi nhân viên sẽ thuộc 1 loại tài khoản nhất định và xác định qua IDType
- [ ] Mỗi nhân viên sẽ được phân biêt với nhau qua IDNV

**TypeAcc(_IDType_, Name)**
- [ ] Môt loại tài khoản sẽ thuộc nhiều nhân viên hoặc nhiều khách hàng

**KhachHang(_IDKH_, IDtype, Email, Pass, TenKH, DiaChi, DienThoai, Avatar)**
- [ ] Hệ thống sẽ lưu trữ thông tin khách hàng khi khách hàng đăng kí tài khoản
- [ ] Mỗi khách hầng sẽ có 1 loại tài khoản nhất định và xác định qua IDType
- [ ] Mỗi khách hàng sẽ được phân biệt với nhau qua IDKH

**MauXe(_IDMau_, IDKM, IDHang, TenXe, GiaBan, HinhAnh1, HinhAnh2, HinhAnh3, BaoHanh, Mota, TrangThai)**
- [ ] Hệ thống lưu trữ thông tin của mẫu xe khi quản lý thêm hoặc cập nhật mẫu xe 
- [ ] Một mẫu xe sẽ có duy nhất 1 hãng xe và 1 hãng xe thì có nhiều mẫu xe
- [ ] Một mẫu xe sẽ có duy nhất 1 khuyến mãi và 1 khuyến mãi có thể dành cho nhiều mẫu xe.
- [ ] Mỗi mẫu xe sẽ được phân biêt với nhau qua IDMau

**HoaDon (_IDHD_, IDKH, NgayDat, TrangThai)**
- [ ] Hệ thống sẽ lưu trữ thông tin đặt hàng và nhân viên sẽ tạo hóa đơn khi khách hàng đặt mua sản phẩm
- [ ] Một khách hàng có thể có 1 hoặc nhiều hóa đơn và 1 hóa đơn chỉ dành cho 1 khách hàng
- [ ] Khách hàng muốn mua sản phẩm (tạo hóa đơn) phải Login
- [ ] Mỗi hóa đơn sẽ được phân biệt với nhau qua IDHD và IDKH
- [ ] Một hóa đơn sẽ có 1 hoặc nhiều chi tiết hóa đơn và chi tiết hóa đơn chỉ dành cho 1 hóa đơn

**ChiTietHoaDon(_IDHD_, _IDXe_, KhuyenMai, GiaBan)**
- [ ] Một hóa đơn có thể có 1 hoặc nhiều xe thông qua chi tiết hóa đơn
- [ ] Chi tiết hóa đơn lưu trữ thông tin về khuyến mãi và giá bán của xe, đề phòng sau này có thể có thay đổi giá bán và khuyến mãi của chiếc xe đó thì hóa đơn sẽ không bị thay đổi

**Xe(_IDXe_, IDMau, TrangThai, TenXe)**
- [ ] Lưu trữ thông tin của xe khi quản lý thêm hoặc cập nhật xe
- [ ] Một xe sẽ thuộc một mẫu xe và mẫu xe có một hoặc nhiều xe
- [ ] Mỗi xe sẽ được phân biệt với nhau qua IDXe

**ChiTietDG(_IDKH_, _IDMau_, NoidungDG)**
- [ ] Hệ thống sẽ lưu thông tin nội dung đánh giá của khách hàng khi khách hàng đánh giá sản phẩm
- [ ] Một khách hàng có thể đánh giá môt hoặc nhiều mẫu xe và mẫu xe có thể đánh giá bởi một hoặc nhiều khách hàng 
- [ ] Mỗi đánh giá sẽ được phân biêt với nhau qua IDKH

**Hang(_IDHang_, TenHang, TrangThai)**
- [ ] Quản lý lưu trữ thông tin của hãng xe khi quản lý thêm hoặc cập nhật hãng xe
- [ ] Mỗi hãng xe sẽ được phân biệt với nhau qua IDHang
- [ ] Một hãng xe có thể thuộc 1 hoặc nhiều mẫu xe và 1 mẫu xe chỉ thuộc 1 hãng xe

**KhuyenMai(_IDKM_, Gia Tri)**
- [ ] Quản lý lưu trữ thông tin của khuyến mãi khi quản lý thêm hoặc cập nhật khuyến mãi
- [ ] Mỗi khuyễn mãi sẽ được phân biệt với nhau qua IDKM
- [ ] Một khuyến mãi có thể thuộc 1 hoặc nhiều mẫu xe và 1 mẫu xe chỉ có 1 khuyễn mãi
**LoaiXe(_IDLoaiXe_, TenLoaiXe)**
- [ ] Quản lý lưu trữ thông tin của loại xe khi quản lý thêm hoặc cập nhật loại xe
- [ ] Mỗi loại xe sẽ được phân biệt với nhau qua IDLoaiXe
- [ ] Một loại xe có thể thuộc 1 hoặc nhiều mẫu xe và 1 mẫu xe chỉ thuộc 1 loại xe 
-
