### ISSUE TITLE
[Dev][Page] - Home Page

### ISSUE THREAD

**Issue by truc-nguyen-vn** [truc-nguyen-vn/CNPMNC-WEB#2]

**Comment by TrucNguyen-HUFLIT** [comment]
- [ ] Main Layout (Header  + NavigationBar + Footer)
- [ ] List Product (Grid)

**Comment by TrucNguyen-HUFLIT** [comment]
- Main Layout (Header + NavigationBar + Footer)
      - [ ] Design Front end (Header + NavigationBar + Footer)
- List Product (Grid)
      - [ ] Design Front end to show Data
      - [ ] Show Data demo
      - [ ] Connect Data (MockData)

**Comment by truc-nguyen-vn** [comment]
- [ ] Đăng nhập
- [ ] Xem giỏ hàng
- [ ] Navigation Bar các hãng xe
- [ ] Hiển thị ảnh xe đẹp
- [ ] Hiển thị danh mục Hãng xe
- [ ] Slide show các Brand nổi tiếng
- [ ] Hiển thị vài Mẫu xe
