### ISSUE TITLE
[Dev][Page] - Manager/Staff Page

### ISSUE THREAD

**Issue by truc-nguyen-vn** [truc-nguyen-vn/CNPMNC-WEB#7]

**Comment by truc-nguyen-vn** [comment]
- Quản lý tài khoản:
  - Khách hàng:
      - [x] Thêm
      - [ ] Cập nhật
  - Nhân viên:
      - [ ] Thêm
      - [ ] Cập nhật
- Quản lý mẫu xe: 
  - [ ] Thêm
  - [ ] Cập nhật
- Quản lý thương hiệu:
  - [ ] Thêm
  - [ ] Cập nhật
- Quản lý đơn hàng:
  - [ ] Thêm
  - [ ] Cập nhật
- Quản lý hóa đơn:
  - [ ] Thêm
  - [ ] Cập nhật

**Comment by TrucNguyen-HUFLIT** [comment]
Database:

- MauXe
